/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class frmBateria extends javax.swing.JDialog
{
    private Thread t;
    private static volatile boolean flag = true;
    private static volatile boolean rodando = false;
    

    /**
     * Creates new form frmBateria
     */
    public frmBateria(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        frmBateria.flag = true;
        
        Controller.Controle controle = new Controller.Controle();
        if(controle.LerArquivoExterno().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Erro na Leitura de arquivo!");
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTextBox = new javax.swing.JTextArea();
        btnExecutar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMediaCountingSort = new javax.swing.JLabel();
        lblMediaQuickSort = new javax.swing.JLabel();
        lblMediaInsertionSort = new javax.swing.JLabel();
        lblMediaBubbleSort = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultados");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        txaTextBox.setEditable(false);
        txaTextBox.setColumns(20);
        txaTextBox.setRows(5);
        jScrollPane1.setViewportView(txaTextBox);

        btnExecutar.setText("Executar");
        btnExecutar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExecutarActionPerformed(evt);
            }
        });

        jLabel1.setText("Média CountingSort:");

        jLabel2.setText("Média QuickSort:");

        jLabel3.setText("Média InsertionSort:");

        jLabel4.setText("Média BubbleSort:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMediaBubbleSort, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExecutar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMediaQuickSort, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMediaCountingSort, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMediaInsertionSort, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMediaCountingSort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMediaQuickSort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExecutar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMediaInsertionSort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMediaBubbleSort, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExecutarActionPerformed
    {//GEN-HEADEREND:event_btnExecutarActionPerformed
        
        if(frmBateria.rodando == false)
        {
            frmBateria.rodando = true;
            t = new Thread(() ->
            {
                Controller.Controle controle = new Controller.Controle();

                double tempo;
                double tempoTotal = 0;
                List<Integer> listaNumeros, listaNumerosDesordenado;
                tempo = 0;

                listaNumerosDesordenado = controle.LerArquivoExterno();

                for(int i = 0; i < 100 && frmBateria.flag == true; i++)
                {
                    listaNumeros = new ArrayList(listaNumerosDesordenado);
                    tempo = controle.countingSort(listaNumeros);
                    txaTextBox.append("CountingSort:: Tempo: "+ tempo + " ms; Tamanho: "+listaNumeros.size()+" \n");
                    listaNumeros.clear();
                    tempoTotal += tempo;
                    lblMediaCountingSort.setText(String.valueOf(tempoTotal/(i+1)));
                }

                tempoTotal = 0;

                for(int i = 0; i < 100 && frmBateria.flag == true; i++)
                {
                    listaNumeros = new ArrayList(listaNumerosDesordenado);
                    tempo = controle.quickSort(listaNumeros);
                    txaTextBox.append("QuickSort:: Tempo: "+ tempo + " ms; Tamanho: "+listaNumeros.size()+" \n");
                    listaNumeros.clear();
                    tempoTotal += tempo;
                    lblMediaQuickSort.setText(String.valueOf(tempoTotal/(i+1)));
                }

                tempoTotal = 0;

                for(int i = 0; i < 100 && frmBateria.flag == true; i++)
                {
                    listaNumeros = new ArrayList(listaNumerosDesordenado);
                    tempo = controle.insertionSort(listaNumeros);
                    txaTextBox.append("InsertionSort:: Tempo: "+ tempo + " ms; Tamanho: "+listaNumeros.size()+" \n");
                    listaNumeros.clear();
                    tempoTotal += tempo;
                    lblMediaInsertionSort.setText(String.valueOf(tempoTotal/(i+1)));
                }

                tempoTotal = 0;

                for(int i = 0; i < 100 && frmBateria.flag == true; i++)
                {
                    listaNumeros = new ArrayList(listaNumerosDesordenado);
                    tempo = controle.bubbleSort(listaNumeros);
                    txaTextBox.append("BubbleSort:: Tempo: "+ tempo + " ms; Tamanho: "+listaNumeros.size()+" \n");
                    listaNumeros.clear();
                    tempoTotal += tempo;
                    lblMediaBubbleSort.setText(String.valueOf(tempoTotal/(i+1)));
                }

                tempoTotal = 0;
                frmBateria.rodando = false;

            });
            t.start();
            
        }
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing

        frmBateria.flag = false;

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmBateria dialog = new frmBateria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMediaBubbleSort;
    private javax.swing.JLabel lblMediaCountingSort;
    private javax.swing.JLabel lblMediaInsertionSort;
    private javax.swing.JLabel lblMediaQuickSort;
    private javax.swing.JTextArea txaTextBox;
    // End of variables declaration//GEN-END:variables
}
