/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controle;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author endrunne
 */
public class frmPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btgOrdenacao = new javax.swing.ButtonGroup();
        btgRandomicoOuExterno = new javax.swing.ButtonGroup();
        lblCriacao = new javax.swing.JLabel();
        btnCriarExportar = new javax.swing.JButton();
        lblOrdenacao = new javax.swing.JLabel();
        rbtBubbleSort = new javax.swing.JRadioButton();
        rbtInsertionSort = new javax.swing.JRadioButton();
        rbtRandomico = new javax.swing.JRadioButton();
        rbtArquivo = new javax.swing.JRadioButton();
        btnOrdenar = new javax.swing.JButton();
        lblTamanho = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        btnBateria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbtQuickSort = new javax.swing.JRadioButton();
        rbtCountingSort = new javax.swing.JRadioButton();
        lblRespostaTempo = new javax.swing.JLabel();
        lblRespostaTamanho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teste de Algoritmos de Ordenação");
        setResizable(false);

        lblCriacao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblCriacao.setText("Criação: ");

        btnCriarExportar.setText("Criar e Exportar Arquivo Externo");
        btnCriarExportar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCriarExportarActionPerformed(evt);
            }
        });

        lblOrdenacao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblOrdenacao.setText("Ordenação:");

        btgOrdenacao.add(rbtBubbleSort);
        rbtBubbleSort.setSelected(true);
        rbtBubbleSort.setText("BubbleSort*");

        btgOrdenacao.add(rbtInsertionSort);
        rbtInsertionSort.setText("InsertionSort");

        btgRandomicoOuExterno.add(rbtRandomico);
        rbtRandomico.setSelected(true);
        rbtRandomico.setText("Criar lista randomica");

        btgRandomicoOuExterno.add(rbtArquivo);
        rbtArquivo.setText("Ler arquivo externo");

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOrdenarActionPerformed(evt);
            }
        });

        lblTamanho.setText("Tamanho:");

        lblTempo.setText("Tempo:");
        lblTempo.setPreferredSize(new java.awt.Dimension(36, 30));

        btnBateria.setText("Fazer Bateria de Testes*");
        btnBateria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBateriaActionPerformed(evt);
            }
        });

        jLabel1.setText("* Pode demorar um pouco");

        btgOrdenacao.add(rbtQuickSort);
        rbtQuickSort.setText("QuickSort");

        btgOrdenacao.add(rbtCountingSort);
        rbtCountingSort.setText("CountingSort");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCriacao)
                    .addComponent(btnCriarExportar)
                    .addComponent(lblOrdenacao)
                    .addComponent(btnOrdenar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRespostaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRespostaTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBateria)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtBubbleSort)
                                    .addComponent(rbtInsertionSort))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbtRandomico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtCountingSort)
                            .addComponent(rbtQuickSort)
                            .addComponent(rbtArquivo)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCriacao)
                .addGap(18, 18, 18)
                .addComponent(btnCriarExportar)
                .addGap(18, 18, 18)
                .addComponent(lblOrdenacao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtBubbleSort)
                    .addComponent(rbtQuickSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtInsertionSort)
                    .addComponent(rbtCountingSort))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtRandomico)
                    .addComponent(rbtArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrdenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespostaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespostaTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        lblTempo.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarExportarActionPerformed

        Controle controle = new Controle();

        if(controle.CriarEExportarArquivo())
        JOptionPane.showMessageDialog(null, "Arquivo criado com sucesso!");

        else
        JOptionPane.showMessageDialog(null, "Erro na Criação de arquivo!");

    }//GEN-LAST:event_btnCriarExportarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed

        Controle controle = new Controle();
        double tempo;
        List<Integer> listaNumeros;

        if(rbtRandomico.isSelected())
            listaNumeros = controle.CriarListaRandomica();

        else
            listaNumeros = controle.LerArquivoExterno();
        
        tempo = 0;

        if(rbtBubbleSort.isSelected())
            tempo = controle.bubbleSort(listaNumeros);

        else if(rbtInsertionSort.isSelected())
            tempo = controle.insertionSort(listaNumeros);
        
        else if(rbtQuickSort.isSelected())
            tempo = controle.quickSort(listaNumeros);
        
        else if(rbtCountingSort.isSelected())
            tempo = controle.countingSort(listaNumeros);

        lblRespostaTempo.setText(String.valueOf(tempo));
        lblRespostaTamanho.setText(String.valueOf(listaNumeros.size()));
        
        if(!controle.isOrdenado(listaNumeros))
            lblTempo.setText("Erro: vetor não ordenado!");

    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgOrdenacao;
    private javax.swing.ButtonGroup btgRandomicoOuExterno;
    private javax.swing.JButton btnBateria;
    private javax.swing.JButton btnCriarExportar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCriacao;
    private javax.swing.JLabel lblOrdenacao;
    private javax.swing.JLabel lblRespostaTamanho;
    private javax.swing.JLabel lblRespostaTempo;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JRadioButton rbtArquivo;
    private javax.swing.JRadioButton rbtBubbleSort;
    private javax.swing.JRadioButton rbtCountingSort;
    private javax.swing.JRadioButton rbtInsertionSort;
    private javax.swing.JRadioButton rbtQuickSort;
    private javax.swing.JRadioButton rbtRandomico;
    // End of variables declaration//GEN-END:variables
}
